<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\SlcWmsT02ShippingInstructionHeader;

class SlcWmsT02ShippingInstructionHeaderTableSeeder extends Seeder
{
    private $data = [
        [
            "オーナーＩＤ" => "000001",
            "倉庫コード" => "wh1",
            "出荷バッチＮＯ" => "Batch1",
            "出荷伝票番号" => "Shipment1",
            "荷主伝票番号" => "Consignor1",
            "得意先コード" => "Customer1",
            "納品先コード" => "Delivery1",
            "受払区分" => "01",
            "出荷予定日" => "20230923",
            "納品予定日" => "20230924",
            "納品先名１" => "Delivery Name 1",
            "納品先名２" => "Delivery Name 2",
            "納品先住所１" => "Delivery Address 1",
            "納品先住所２" => "Delivery Address 2",
            "納品先電話番号" => "1234567890",
            "納品先ＦＡＸ番号" => "0987654321",
            "納品先郵便番号" => "12345",
            "得意先名１" => "Customer Name 1",
            "得意先名２" => "Customer Name 2",
            "得意先住所１" => "Customer Address 1",
            "得意先住所２" => "Customer Address 2",
            "得意先電話番号" => "9876543210",
            "得意先ＦＡＸ番号" => "1234567890",
            "得意先郵便番号" => "54321",
            "店舗コード" => "st1",
            "店名" => "st Name 1",
            "配送先ルートコード" => "Route1",
            "配送先ルート名" => "Route Name 1",
            "バッチＮＯ" => "Batch Number 1",
            "荷送人コード" => "Shipper1",
            "荷送人名称１" => "Shipper Name 1",
            "荷送人名称２" => "Shipper Name 2",
            "荷送人住所１" => "Shipper Address 1",
            "荷送人住所２" => "Shipper Address 2",
            "荷送人電話番号" => "9876543210",
            "荷送人ＦＡＸ番号" => "1234567890",
            "荷送人郵便番号" => "54321",
            "発注者名称１" => "Orderer Name 1",
            "発注者名称２" => "Orderer Name 2",
            "発注者住所１" => "Orderer Address 1",
            "発注者住所２" => "Orderer Address 2",
            "発注者電話番号" => "1234567890",
            "発注者ＦＡＸ番号" => "0987654321",
            "発注者郵便番号" => "12345",
            "荷主コード" => "Cargo 00001",
            "ヘッダ備考１" => "Header Note 1",
            "ヘッダ備考２" => "Header Note 2",
            "ヘッダ備考３" => "Header Note 3",
            "ヘッダ備考４" => "Header Note 4",
            "ヘッダ備考５" => "Header Note 5",
            "伝票区分１" => "01",
            "伝票区分２" => "02",
            "伝票区分３" => "03",
            "伝票区分４" => "04",
            "伝票区分５" => "05",
            "引当フラグ" => "Y",
            "確定フラグ" => "Y",
            "予備１" => "Reserved1",
            "予備２" => "Reserved2",
            "予備３" => "Reserved3",
            "予備４" => "Reserved4",
            "予備５" => "Reserved5",
            "予備６" => "Reserved6",
            "予備７" => "Reserved7",
            "予備８" => "Reserved8",
            "予備９" => "Reserved9",
            "予備１０" => "Reserved10",
            "数値予備１" => 1234.5678,
            "数値予備２" => 5678.1234,
            "数値予備３" => 9876.5432,
            "数値予備４" => 5432.9876,
            "数値予備５" => 1000.1111,
            "作成日時" => "2023-09-23 10:00:00",
            "作成者コード" => "Creator1",
            "更新日時" => "2023-09-23 10:30:00",
            "更新者コード" => "Updater1",
            "更新プログラム" => "Program1",
            "出庫料有無" => "Y",
            "追加作業付加" => "Y",
            "納品書番号" => "Delivery Number 1",
            "ピッキングリスト発行フラグ" => "Y",
            "納品書発行フラグ" => "Y"
        ],
        [
            "オーナーＩＤ" => "000002",
            "倉庫コード" => "wh2",
            "出荷バッチＮＯ" => "Batch2",
            "出荷伝票番号" => "Shipment2",
            "荷主伝票番号" => "Consignor2",
            "得意先コード" => "Customer2",
            "納品先コード" => "Delivery2",
            "受払区分" => "02",
            "出荷予定日" => "20230924",
            "納品予定日" => "20230925",
            "納品先名１" => "Delivery Name 3",
            "納品先名２" => "Delivery Name 4",
            "納品先住所１" => "Delivery Address 3",
            "納品先住所２" => "Delivery Address 4",
            "納品先電話番号" => "1357924680",
            "納品先ＦＡＸ番号" => "2468013579",
            "納品先郵便番号" => "54321",
            "得意先名１" => "Customer Name 3",
            "得意先名２" => "Customer Name 4",
            "得意先住所１" => "Customer Address 3",
            "得意先住所２" => "Customer Address 4",
            "得意先電話番号" => "2468013579",
            "得意先ＦＡＸ番号" => "1357924680",
            "得意先郵便番号" => "12345",
            "店舗コード" => "st2",
            "店名" => "st Name 2",
            "配送先ルートコード" => "Route2",
            "配送先ルート名" => "Route Name 2",
            "バッチＮＯ" => "Batch Number 2",
            "荷送人コード" => "Shipper2",
            "荷送人名称１" => "Shipper Name 3",
            "荷送人名称２" => "Shipper Name 4",
            "荷送人住所１" => "Shipper Address 3",
            "荷送人住所２" => "Shipper Address 4",
            "荷送人電話番号" => "1357924680",
            "荷送人ＦＡＸ番号" => "2468013579",
            "荷送人郵便番号" => "54321",
            "発注者名称１" => "Orderer Name 3",
            "発注者名称２" => "Orderer Name 4",
            "発注者住所１" => "Orderer Address 3",
            "発注者住所２" => "Orderer Address 4",
            "発注者電話番号" => "2468013579",
            "発注者ＦＡＸ番号" => "1357924680",
            "発注者郵便番号" => "12345",
            "荷主コード" => "Cargo 00002",
            "ヘッダ備考１" => "Header Note 3",
            "ヘッダ備考２" => "Header Note 4",
            "ヘッダ備考３" => "Header Note 5",
            "ヘッダ備考４" => "Header Note 6",
            "ヘッダ備考５" => "Header Note 7",
            "伝票区分１" => "11",
            "伝票区分２" => "12",
            "伝票区分３" => "13",
            "伝票区分４" => "14",
            "伝票区分５" => "15",
            "引当フラグ" => "N",
            "確定フラグ" => "N",
            "予備１" => "Reserved11",
            "予備２" => "Reserved12",
            "予備３" => "Reserved13",
            "予備４" => "Reserved14",
            "予備５" => "Reserved15",
            "予備６" => "Reserved16",
            "予備７" => "Reserved17",
            "予備８" => "Reserved18",
            "予備９" => "Reserved19",
            "予備１０" => "Reserved20",
            "数値予備１" => 9876.5432,
            "数値予備２" => 1000.1111,
            "数値予備３" => 1234.5678,
            "数値予備４" => 5678.1234,
            "数値予備５" => 5432.9876,
            "作成日時" => "2023-09-24 09:30:00",
            "作成者コード" => "Creator2",
            "更新日時" => "2023-09-24 10:45:00",
            "更新者コード" => "Updater2",
            "更新プログラム" => "Program2",
            "出庫料有無" => "N",
            "追加作業付加" => "N",
            "納品書番号" => "Delivery Number 2",
            "ピッキングリスト発行フラグ" => "N",
            "納品書発行フラグ" => "N"
        ],
        [
            "オーナーＩＤ" => "000003",
            "倉庫コード" => "wh3",
            "出荷バッチＮＯ" => "Batch3",
            "出荷伝票番号" => "Shipment3",
            "荷主伝票番号" => "Consignor3",
            "得意先コード" => "Customer3",
            "納品先コード" => "Delivery3",
            "受払区分" => "03",
            "出荷予定日" => "20230925",
            "納品予定日" => "20230926",
            "納品先名１" => "Delivery Name 5",
            "納品先名２" => "Delivery Name 6",
            "納品先住所１" => "Delivery Address 5",
            "納品先住所２" => "Delivery Address 6",
            "納品先電話番号" => "9876543210",
            "納品先ＦＡＸ番号" => "1234567890",
            "納品先郵便番号" => "54321",
            "得意先名１" => "Customer Name 5",
            "得意先名２" => "Customer Name 6",
            "得意先住所１" => "Customer Address 5",
            "得意先住所２" => "Customer Address 6",
            "得意先電話番号" => "1234567890",
            "得意先ＦＡＸ番号" => "9876543210",
            "得意先郵便番号" => "12345",
            "店舗コード" => "st3",
            "店名" => "st Name 3",
            "配送先ルートコード" => "Route3",
            "配送先ルート名" => "Route Name 3",
            "バッチＮＯ" => "Batch Number 3",
            "荷送人コード" => "Shipper3",
            "荷送人名称１" => "Shipper Name 5",
            "荷送人名称２" => "Shipper Name 6",
            "荷送人住所１" => "Shipper Address 5",
            "荷送人住所２" => "Shipper Address 6",
            "荷送人電話番号" => "9876543210",
            "荷送人ＦＡＸ番号" => "1234567890",
            "荷送人郵便番号" => "54321",
            "発注者名称１" => "Orderer Name 5",
            "発注者名称２" => "Orderer Name 6",
            "発注者住所１" => "Orderer Address 5",
            "発注者住所２" => "Orderer Address 6",
            "発注者電話番号" => "1234567890",
            "発注者ＦＡＸ番号" => "9876543210",
            "発注者郵便番号" => "12345",
            "荷主コード" => "Cargo 00003",
            "ヘッダ備考１" => "Header Note 8",
            "ヘッダ備考２" => "Header Note 9",
            "ヘッダ備考３" => "Header Note 10",
            "ヘッダ備考４" => "Header Note 11",
            "ヘッダ備考５" => "Header Note 12",
            "伝票区分１" => "21",
            "伝票区分２" => "22",
            "伝票区分３" => "23",
            "伝票区分４" => "24",
            "伝票区分５" => "25",
            "引当フラグ" => "Y",
            "確定フラグ" => "Y",
            "予備１" => "Reserved21",
            "予備２" => "Reserved22",
            "予備３" => "Reserved23",
            "予備４" => "Reserved24",
            "予備５" => "Reserved25",
            "予備６" => "Reserved26",
            "予備７" => "Reserved27",
            "予備８" => "Reserved28",
            "予備９" => "Reserved29",
            "予備１０" => "Reserved30",
            "数値予備１" => 1234.5678,
            "数値予備２" => 5678.1234,
            "数値予備３" => 9876.5432,
            "数値予備４" => 5432.9876,
            "数値予備５" => 1000.1111,
            "作成日時" => "2023-09-25 08:15:00",
            "作成者コード" => "Creator3",
            "更新日時" => "2023-09-25 09:45:00",
            "更新者コード" => "Updater3",
            "更新プログラム" => "Program3",
            "出庫料有無" => "Y",
            "追加作業付加" => "Y",
            "納品書番号" => "Delivery Number 3",
            "ピッキングリスト発行フラグ" => "Y",
            "納品書発行フラグ" => "Y"
        ]
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $currentDate = Carbon::now();

        // $counter = 0;
        // for ($index = 1; $index <= 20; $index++) {
        //     if ($counter % 3 === 0 && $counter > 0) {
        //         $currentDate->addDay();
        //     }
        //     SlcWmsT02ShippingInstructionHeader::factory()->estimatedShippingDate($currentDate->format('Ymd'))->create();
        //     $counter++;
        // }
        DB::table('ＷＭＳ＿Ｔ１０２出荷指示ヘッダ')->truncate();
        DB::table('ＷＭＳ＿Ｔ１０２出荷指示ヘッダ')->insert($this->data);
    }
}
